//This file was generated by the EDT compiler. Do not edit it.
class _Users_mahmood1_Work_edt_test_example_edt extends EDTemplate {
  String render(Map data, OutputStream out) {
    out.writeString("<html>\n <head>\n 	<title>");
    out.writeString("\n    Here a title content\n");
    out.writeString("</title>\n 	");
    out.writeString("\n    <sript type=\"text/javascript\" src=\"\"></script>\n");
    out.writeString("\n <head>\n <body>\n 	");
    out.writeString("\n 	");
    out.writeString("<div>\n	<span>Include content</span>\n	<span>");
    out.writeString(escapeHtml(data["third"]));
    out.writeString("</span>\n	<span>");
    out.writeString(data["forth"]);
    out.writeString("</span>\n</div>");
    out.writeString("\n 	<div>\n 	   ");
 if (data["condition"]) { 
    out.writeString("\n 	   		<span>");
    out.writeString(escapeHtml(data["one"]));
    out.writeString("</span>\n 	   		<span>");
    out.writeString(data["second"]);
    out.writeString("</span>\n 	   ");
 } 
    out.writeString(" 	\n 	</div>");
    out.writeString("\n </body>\n</html>");
  }
}
